upstreamProjects:
  Mule-runtime/mule/master-JUNE-2025
mavenSettingsXmlId: mule-runtime-maven-settings-MuleSettings
archiveArtifacts: "**/hs_*.log"
projectType: runtime
mavenTool: "3.9.9"
jdkTool: OPEN-JDK17
additionalTestConfigs:
  jdk21:
    testJdkTool: TEMURIN-JDK21
